增加Run日本攻略
The-Run-Philosophy-Organization/run pull request #163
Opened 2022-04-17 13:29 UTC by YoungDriverOfTech

Run日本难度低，这些内容应该会对一些自身条件不怎么好的同学有帮助

2022-04-17 20:19 UTC, the-run-philosophy approved these changes

2022-04-17 20:20 UTC, the-run-philosophy requested changes

2022-04-17 20:20 UTC, the-run-philosophy commented on 润学方法论/各国选择/日本/readme.md
> +![四重奏](sichongzou.jpeg)
文件名可以直接用中文。。

2022-04-17 20:27 UTC, the-run-philosophy requested changes

2022-04-17 20:27 UTC, the-run-philosophy commented on 润学方法论/各国选择/日本/readme.md
> +![无法成为野兽的我们](wufachengweiyeshoudewomen.jpeg)
请直接使用中文，而不是拼音

2022-04-17 20:27 UTC, the-run-philosophy commented on 润学方法论/各国选择/日本/readme.md
> +![半泽直树](banzezhishu.jpeg)
请直接使用中文，而不是拼音

2022-04-17 20:27 UTC, the-run-philosophy commented on 润学方法论/各国选择/日本/readme.md
> +![APPLogo](ujob.png)
请直接使用中文，而不是拼音

2022-04-17 20:27 UTC, the-run-philosophy commented on 润学方法论/各国选择/日本/readme.md
> +![标准日本语](biaori.jpeg)
请直接使用中文，而不是拼音

2022-04-17 20:27 UTC, the-run-philosophy commented on 润学方法论/各国选择/日本/readme.md
> +![红宝书蓝宝书](honglanbaoshu.jpeg)
请直接使用中文，而不是拼音

2022-04-17 23:23 UTC, YoungDriverOfTech commented on 润学方法论/各国选择/日本/readme.md
> +![四重奏](sichongzou.jpeg)
已修正

2022-04-17 23:23 UTC, YoungDriverOfTech commented on 润学方法论/各国选择/日本/readme.md
> +![无法成为野兽的我们](wufachengweiyeshoudewomen.jpeg)
已修正

2022-04-17 23:23 UTC, YoungDriverOfTech commented on 润学方法论/各国选择/日本/readme.md
> +![半泽直树](banzezhishu.jpeg)
已修正

2022-04-17 23:24 UTC, YoungDriverOfTech commented on 润学方法论/各国选择/日本/readme.md
> +![APPLogo](ujob.png)
已修正

2022-04-17 23:24 UTC, YoungDriverOfTech commented on 润学方法论/各国选择/日本/readme.md
> +![标准日本语](biaori.jpeg)
已修正

2022-04-17 23:24 UTC, YoungDriverOfTech commented on 润学方法论/各国选择/日本/readme.md
> +![红宝书蓝宝书](honglanbaoshu.jpeg)
已修正

2022-04-18 04:14 UTC, the-run-philosophy commented
thanks

2022-04-18 04:14 UTC, the-run-philosophy approved these changes

2022-04-18 04:14 UTC, merged