feat: polish all posts.
The-Run-Philosophy-Organization/run pull request #219
Opened 2022-04-21 12:40 UTC by Xnor-bear

## 概述

> 优化全部文档排版。

## 参考资料

- 中文文案排版指南：<https://github.com/mzlogin/chinese-copywriting-guidelines>
- Markdownlint Rules：<https://github.com/DavidAnson/markdownlint/blob/v0.25.1/doc/Rules.md>

## 主要工作

- 中英文添加空格（ref: [為什麼你們就是不能加個空格呢？](https://github.com/vinta/pangu.js)）
- 使用直角引号
- 使用正确缩写（指 Alias）格式
- 规范的 Markdown 语法与格式
- 删除多余空格
- 解决全半角符号混用
- 统一裸连接（bare url）格式

## 特殊处理

### 人口问题相关/

- 生育率数据.md

删除多余空格

- 黄文政观点.md

替换全角数字为半角数字
去除错误的段落换行

### 哲学概念/

- 中国的网络审查.md

替换半角括号匹配前方全角括号

- 从沉默成本谬误到损失厌恶情结.md

优化原版灾难级的排版
将方头括号内部内容加粗并移除方头括号
原文链接格式修正
移除无效缩进

- 布尔什维克.md

引用格式修正
移除无用引用标志

- 法家和秦制.md

根据原文修正排版
移除无用缩进

- 统治的三种形态.md

移除无用引用标志
使用正确的省略号
无序列表正确缩进

- 言论自由.md

移除无用引用标志

### 张维为陈平曹丰泽等知名言论收集/

#### -陈平/

- README.md

补全句号 格式统一
陈平不等式.md
正确换行
 
### 外交部发言精选/

- README.md

目录补全 删除无意义图片

### 润学实例/

#### -计算机/

- 如何在国内申请美国绿卡.md

正确使用标点

- 浙大本科美国三本佛罗里达数据工程师.md

替换全角数字为半角数字

### 润学感悟/

-为了更好的润，我心中的润学.md

删除大量无用空格
替换半角符号为全角数字（Why Not?）
使用正确的省略号

- 全世界可口可乐到底是不是一个味道.md

使用正确的省略号

- 棱镜.md

删除多余空格
移除重复标点
改正错字

- 美丽新世界.md

移除无效缩进
使用正确的省略号

### 润学方法论/

-README.md

移除重复标点

- 如何寻找适合自己的方案.md
修正重复的方案6

#### -前期准备/

##### --英语学习/

- 学好英文的十个步骤.md

使用书名号表示书籍

#### -各国选择/

##### --GDP排名前20的国家/

- README.md

改正错字
修正超链接格式

##### --加拿大/

- 加拿大各省提名具体要求.md

修正文档错误

##### --墨西哥/

- README.md

删除无用标题

##### --美国/

- 北美王探长：美国EB-5投资移民签证实操圣经.md

优化文章结构
移除重复标点

##### --西欧北欧/

- 芬兰留学移民优缺点.md

使用加粗而非标题实现强调
统一无序列表符号

2022-04-21 16:12 UTC, the-run-philosophy commented on README.md
> +> 提交 B 站等国内平台的视频链接请移除追踪参数。
@Xnor-bear  i don't think this make sense...

2022-04-21 16:23 UTC, the-run-philosophy requested changes
单纯应用修改模版有问题，需要手动修改。

2022-04-22 20:06 UTC, Himself65 approved these changes

2022-04-22 21:03 UTC, Himself65 requested changes
LGTM if resolve conflicts

2022-04-22 21:24 UTC, Himself65 commented
Refs: #233

2022-04-23 23:42 UTC, closed without merging