更新
The-Run-Philosophy-Organization/run pull request #238
Opened 2022-04-23 05:06 UTC by jiayouba233

1. 移除了 #232  的第三方链接 捅 #146 
2.更新了 新冠疫情相关，移除视频替换为Youtube链接（并提供IPFS备份链接），防止仓库占用空间过大
3.再次更新 润学感悟中 为了更好的润，我心中的润学

2022-04-23 19:57 UTC, the-run-philosophy requested changes
看comments

2022-04-23 19:57 UTC, the-run-philosophy commented on 新冠疫情相关/README.md
> + ![image](https://github.com/The-Run-Philosophy-Organization/run/raw/main/%E5%A4%96%E4%BA%A4%E9%83%A8%E5%8F%91%E8%A8%80%E7%B2%BE%E9%80%89/%E8%B5%B5%E7%AB%8B%E5%9D%9A/%E5%81%B7%E7%9D%80%E4%B9%90.jpg)
改为本地中文目录？

2022-04-24 02:05 UTC, jiayouba233 commented on 新冠疫情相关/README.md
> + ![image](https://github.com/The-Run-Philosophy-Organization/run/raw/main/%E5%A4%96%E4%BA%A4%E9%83%A8%E5%8F%91%E8%A8%80%E7%B2%BE%E9%80%89/%E8%B5%B5%E7%AB%8B%E5%9D%9A/%E5%81%B7%E7%9D%80%E4%B9%90.jpg)
> 改为本地中文目录？

fix，请求Merge

2022-04-24 04:23 UTC, the-run-philosophy approved these changes
thanks

2022-04-24 04:23 UTC, merged