增加金融时报的报道
The-Run-Philosophy-Organization/run pull request #242
Opened 2022-04-23 20:09 UTC by stackunderflow111

2022-04-23 20:11 UTC, the-run-philosophy requested changes

2022-04-23 20:11 UTC, the-run-philosophy commented on 媒体报道/‘Voting with their feet’: China’s wealthy look to leave after Shanghai lockdown.md
> +# ‘Voting with their feet’: China’s wealthy look to leave after Shanghai lockdown
请修改文件名。

2022-04-23 20:17 UTC, stackunderflow111 commented on 媒体报道/‘Voting with their feet’: China’s wealthy look to leave after Shanghai lockdown.md
> +# ‘Voting with their feet’: China’s wealthy look to leave after Shanghai lockdown
怎样修改比较好

2022-04-23 20:20 UTC, the-run-philosophy commented on 媒体报道/‘Voting with their feet’: China’s wealthy look to leave after Shanghai lockdown.md
> +# ‘Voting with their feet’: China’s wealthy look to leave after Shanghai lockdown
用简短的中文名即可

2022-04-23 20:21 UTC, the-run-philosophy commented on 媒体报道/‘Voting with their feet’: China’s wealthy look to leave after Shanghai lockdown.md
> +# ‘Voting with their feet’: China’s wealthy look to leave after Shanghai lockdown
另外建议增加全文，进行合适的版权声明即可

2022-04-23 20:23 UTC, stackunderflow111 commented on 媒体报道/‘Voting with their feet’: China’s wealthy look to leave after Shanghai lockdown.md
> +# ‘Voting with their feet’: China’s wealthy look to leave after Shanghai lockdown
你可以试试去金融时报网站上复制粘贴，他们会在开头加上“你的行为侵犯版权”。我想了想还是给链接算了。

2022-04-24 03:26 UTC, the-run-philosophy commented on 媒体报道/‘Voting with their feet’: China’s wealthy look to leave after Shanghai lockdown.md
> +# ‘Voting with their feet’: China’s wealthy look to leave after Shanghai lockdown
ok, 英文报道没啥价值。。有中文版吗？

2022-04-24 04:22 UTC, the-run-philosophy commented
please re-PR with chinese version~

2022-04-24 04:22 UTC, closed without merging