修正四月之声路径
The-Run-Philosophy-Organization/run pull request #259
Opened 2022-04-24 19:57 UTC by tonyqus

我发现之前的mp4变404了，所以提交了这个PR

2022-04-24 20:51 UTC, the-run-philosophy requested changes

2022-04-24 20:51 UTC, the-run-philosophy commented on README.md
> -- [存档：上海"四月无声"简短纪录片](新冠疫情相关/上海_四月无声_简短纪录片.mp4)
请保留本地文件？

2022-04-24 20:55 UTC, tonyqus commented on README.md
> -- [存档：上海"四月无声"简短纪录片](新冠疫情相关/上海_四月无声_简短纪录片.mp4)
我没删本地文件，是我发现你们那个mp4 404了，是github删的？

2022-04-24 20:58 UTC, xuanll commented on README.md
> -- [存档：上海"四月无声"简短纪录片](新冠疫情相关/上海_四月无声_简短纪录片.mp4)
确实404了，我也想问

2022-04-25 03:02 UTC, jiayouba233 commented on README.md
> -- [存档：上海"四月无声"简短纪录片](新冠疫情相关/上海_四月无声_简短纪录片.mp4)
> 确实404了，我也想问

是我删除的，见 #238

2022-04-25 03:03 UTC, jiayouba233 commented on README.md
> -- [存档：上海"四月无声"简短纪录片](新冠疫情相关/上海_四月无声_简短纪录片.mp4)
估计是我其他链接忘记做了修改（

2022-04-25 04:36 UTC, the-run-philosophy approved these changes

2022-04-25 04:36 UTC, merged