更新
The-Run-Philosophy-Organization/run pull request #312
Opened 2022-05-02 10:32 UTC by jiayouba233

1.Actions添加检查MarkDown链接是否有效（目前的检查由于未知原因，一亩三分地和 marlabs 的检查结果返回403）
2.移除 失效/第三方 链接

2022-05-02 10:57 UTC, jiayouba233 commented
Update：[一亩三分地](https://github.com/harryhare/1point3acres/issues/18)由于Cloudflare的原因检查结果为 503

2022-05-02 20:55 UTC, the-run-philosophy commented
@jiayouba233  thanks,  能否把修复链接的部分和新增CHECK的部分分开。先修复，再CHECK。这个CHECK现在也无法PASS，就不能MERGE

2022-05-02 20:56 UTC, the-run-philosophy commented
@Himself65  能否帮看看？

2022-05-02 23:58 UTC, the-run-philosophy approved these changes

2022-05-02 23:59 UTC, the-run-philosophy requested changes
please rebase and remove the links.yml for now. fix it later.

2022-05-03 04:24 UTC, the-run-philosophy approved these changes

2022-05-03 04:25 UTC, merged

2022-05-03 07:23 UTC, jiayouba233 commented
> @Himself65 能否帮看看？

#313 我开了个Issue