Update README.md
The-Run-Philosophy-Organization/run pull request #360
Opened 2022-05-12 00:26 UTC by shilong-chan

add 疫情期间强制隔离导致的民愤 pic

2022-05-12 18:54 UTC, bboczeng approved these changes

2022-05-13 02:23 UTC, Himself65 requested changes
可以将图片存到项目中吗？

2022-05-13 04:37 UTC, the-run-philosophy requested changes
请将图片保存到本地

2022-05-14 05:12 UTC, the-run-philosophy approved these changes

2022-05-14 05:12 UTC, merged