Update
The-Run-Philosophy-Organization/run pull request #437
Opened 2022-05-30 16:22 UTC by jiayouba233

1. 将所有 Cl 整合为一个 Check ,并添加 Space 检查的 Cl
2. 添加 中文与符号和数字 之间的空格
3. 网络民议部分添加 专家称入室消毒能有效阻止病毒传播 和 布林肯和华姐说了什么
4. 更新 中国的性少数群体现状.md

2022-05-30 16:24 UTC, jiayouba233 commented
这个 Space 检查似乎有些问题？

2022-05-31 09:09 UTC, the-run-philosophy commented
`添加 中文与符号和数字 之间的空格` 并不符合阅读习惯，请去除。

2022-05-31 09:10 UTC, the-run-philosophy requested changes
添加 中文与符号和数字 之间的空格 并不符合阅读习惯，请去除。
另外请添加多个pr，不要一次性整合一个超大的pr
比如我建议把3，4分成2个pr提交；
1，2待议

2022-05-31 09:38 UTC, closed without merging

2022-06-03 11:18 UTC, jiayouba233 commented
@Himself65