Update
The-Run-Philosophy-Organization/run pull request #438
Opened 2022-05-31 10:09 UTC by jiayouba233

1. 合并 Cl
2. 内宣 网络民议 部分添加 ```专家称入室消毒能有效阻止病毒传播``` 和 ```布林肯和华姐说了什么```
3. 润学感悟添加 一个失去理智的司机有多危险.md
4. 更新 润学感悟/中国的性少数群体现状.md

2022-05-31 10:10 UTC, jiayouba233 commented
#437 所以应该添加的是 中文与英文和数字之间的空格？

2022-06-01 04:26 UTC, the-run-philosophy commented
内宣 网络民议 部分添加 专家称入室消毒能有效阻止病毒传播 和 布林肯和华姐说了什么
润学感悟添加 一个失去理智的司机有多危险.md
更新 润学感悟/中国的性少数群体现状.md
这三者能单独先合并么。
CI的问题以后再说
数字/英文和汉字之间不需要空格吧。

2022-06-01 04:26 UTC, the-run-philosophy requested changes
内宣 网络民议 部分添加 专家称入室消毒能有效阻止病毒传播 和 布林肯和华姐说了什么
润学感悟添加 一个失去理智的司机有多危险.md
更新 润学感悟/中国的性少数群体现状.md
这三者能单独先合并么。
CI的问题以后再说
数字/英文和汉字之间不需要空格吧。

2022-06-02 05:52 UTC, jiayouba233 commented
Fix

2022-06-03 08:31 UTC, the-run-philosophy commented
@jiayouba233  看了你的file changed并没有fix，请确保所有字母和数字前后没有空格。

2022-06-03 08:31 UTC, the-run-philosophy requested changes
看了你的file changed并没有fix，请确保所有字母和数字前后没有空格。
能够把CI的变化去掉吗

2022-06-03 08:53 UTC, jiayouba233 commented
> 看了你的file changed并没有fix，请确保所有字母和数字前后没有空格。 能够把CI的变化去掉吗

我检查了一下，实际上中文与数字之间应该是需要有空格的（

2022-06-03 11:08 UTC, jiayouba233 commented
https://www.w3.org/TR/clreq/

这是中文排版需求的文档

2022-06-05 10:06 UTC, the-run-philosophy commented
`中文排版之需求与问题；另一方面也提供与既有标准（如Unicode）的对应，冀求通过本文有效地促进实现。`

这是里面的原文，你看到Unicode有空格吗

这不符合中国人的使用习惯。

2022-06-05 10:07 UTC, the-run-philosophy commented
我帮你把其他内容Refactor出来了，以后不要改这部分CI了，没有必要而且严重损害阅读体验。

2022-06-05 10:07 UTC, the-run-philosophy commented
这是一群不用中文的人脑子做梦想出来的“规范”。

2022-06-05 10:08 UTC, closed without merging